### PR TITLE
Accept "0X" as a hex prefix

### PR DESCRIPTION
**Pull request by danrice-square**
See https://github.com/square/wire/issues/212.

### CODE REVIEW

**Comment by zachmargolis** [comment]
tests?

**Comment by JakeWharton** [comment]
`protoc` allows this? I have never seen uppercase "X" used.

**Comment by zachmargolis** [comment]
@JakeWharton yup! appears so: https://github.com/google/protobuf/blob/242fdef65a3eb681ce686c0a68c7d33d4fb2ea1a/src/google/protobuf/io/tokenizer_unittest.cc#L213

**Comment by JakeWharton** [comment]
So gross. But yeah, simple test case and LGTM.

**Pull request merged**
