### PR TITLE
Rename ProtoSchemaParser to ProtoParser.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by zachmargolis** [comment]
Update `README.md` too?

**Comment by zachmargolis** [comment]
:+1: tho

**Comment by swankjesse** [comment]
LGTM

Motivation?

**Comment by JakeWharton** [comment]
Same name of the lib, shorter, and... that's about it.

**Comment by swankjesse** [comment]
Sounds good. Original motivation was to avoid being misunderstood as a thing that parses proto binaries. I don't think that every happened!

**Comment by swankjesse** [comment]
(especially since _parser_ evokes text.)

**Pull request merged**
